target("auto-cli")
    set_kind("static")
    set_languages("c++20", {public = true})
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_includedirs("src", {private = true})
    add_headerfiles("include/auto-cli/auto-cli.h")