set_project("auto-cli")
set_version("0.1.0")
set_languages("c++23")

target("auto-cli")
    set_kind("static")
    set_languages("c++20", {public = true})
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_includedirs("include/auto-cli/detail", {private = true})
    add_includedirs("src", {private = true})